/*
image size - 679px × 829px
*/
export default {
	products: [
		{
			_id: '1',
			name: 'Nike Slim shirt',
			category: 'Shirts',
			image: '/assets/img/product-1.jpg',
			price: 120,
			brand: 'Nike',
			countInStock: 10,
			numReviews: 10,
			rating: 4.5,
		},
		{
			_id: '2',
			name: 'Nike Slim shirt',
			category: 'Shirts',
			image: '/assets/img/product-1.jpg',
			price: 120,
			brand: 'Nike',
			countInStock: 10,
			numReviews: 10,
			rating: 4.5,
		},
		{
			_id: '3',
			name: 'Nike Slim shirt',
			category: 'Shirts',
			image: '/assets/img/product-1.jpg',
			price: 120,
			brand: 'Nike',
			countInStock: 10,
			numReviews: 10,
			rating: 4.5,
		},
		{
			_id: '4',
			name: 'Nike Slim shirt',
			category: 'Shirts',
			image: '/assets/img/product-1.jpg',
			price: 120,
			brand: 'Nike',
			countInStock: 10,
			numReviews: 10,
			rating: 4.5,
		},
		{
			_id: '5',
			name: 'Nike Slim shirt',
			category: 'Shirts',
			image: '/assets/img/product-1.jpg', 
			price: 120,
			brand: 'Nike',
			countInStock: 10,
			numReviews: 10,
			rating: 4.5,
		},
		{
			_id: '6',
			name: 'Nike Slim shirt',
			category: 'Shirts',
			image: '/assets/img/product-1.jpg',
			price: 120,
			brand: 'Nike',
			countInStock: 10,
			numReviews: 10,
			rating: 4.5,
		},
	],
};
